version: "3"

networks:
    appnetwork:

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
        - "2181:2181"
    environment: 
        ZOOKEEPER_CLIENT_PORT: 2181 
    networks:
        - appnetwork
  
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on: 
        - zookeeper
    ports:
        - "9092:9092"
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks: 
        - appnetwork

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
        - "9000:9000"
    depends_on: 
        - kafka
    networks: 
        - appnetwork
    environment: 
        KAFKA_BROKERCONNECT: kafka:29092
        SERVER_SERVLET_CONTEXTPATH: "/"
    
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - appnetwork

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - appnetwork
